/* ==========================================================================
   satz-data.js — Satzkreis / Satzleiter base sentences + model answers
   --------------------------------------------------------------------------
   Single source of truth for the sentence-drill content, shared by
   workbooks/satztraining.html (the full interactive drill with structure
   checks) and reels/ (the swipe-through revision mode). Content itself is
   lifted verbatim from workbooks/B2/workbook-7-satzkreis.html and
   workbooks/B1/workbook-8-satzleiter.html — keep all three in sync if it
   changes.
   ========================================================================== */
window.DW_SATZ = (function () {
  "use strict";

  var SATZKREIS = [
    { base: "Das Wetter ist schön.", steps: [
      { s: "Station 1 · Grundformen", p: "Aussage, Verneinung, Ja/Nein-Frage.",
        a: "Das Wetter ist schön. / Das Wetter ist nicht schön. / Ist das Wetter schön?",
        w: "„nicht“ verneint das Adjektiv; in der Frage steht das Verb an Position 1." },
      { s: "Station 2 · Wortwechsel + Angaben", p: "Tausche das Prädikativ und füge eine Zeit-/Grad-Angabe hinzu (2–3 Varianten).",
        a: "Das Wetter ist heute schlecht. / … gerade ziemlich wechselhaft. / … im Moment drückend heiß.",
        w: "Prädikativ nach „sein“ wird nicht dekliniert." },
      { s: "Station 3 · Futur I", p: "Als Vorhersage und als Vermutung über die Gegenwart.",
        a: "Das Wetter wird morgen schön sein. / Das Wetter wird jetzt wohl schön sein.",
        w: "„werden“ Position 2, Infinitiv „sein“ am Ende; „wohl“ macht die Gegenwartsvermutung." },
      { s: "Station 4 · Modalverben", p: "Zwei Modalverben: eigene Vermutung + fremde Aussage.",
        a: "Das Wetter müsste eigentlich schön sein. / Das Wetter soll am Wochenende schön werden.",
        w: "„müsste/dürfte“ = Vermutung des Sprechers; „soll“ = fremde Quelle." },
      { s: "Station 5 · Vergangenheit", p: "Präteritum und Perfekt.",
        a: "Das Wetter war schön. / Das Wetter ist schön gewesen.",
        w: "„sein“ bildet das Perfekt mit „ist“ + „gewesen“." },
      { s: "Station 6 · Modalverb + Vergangenheit", p: "Real (Präteritum) und irreal (hätte + Infinitiv + Modalinfinitiv).",
        a: "Das Wetter sollte am Wochenende schön werden. / Das Wetter hätte schön sein können.",
        w: "Präteritum fürs Reale; „hätte … sein können“ für die verpasste Möglichkeit." },
      { s: "Station 7 · Konjunktiv II", p: "Irrealis Gegenwart, Irrealis Vergangenheit, Wunsch.",
        a: "Das Wetter wäre schön, wenn die Sonne schiene. / … wäre schön gewesen, wenn es nicht geregnet hätte. / Ich wünschte, das Wetter wäre schön.",
        w: "„wäre“ = Konj. II von sein; Vergangenheit = „wäre … gewesen“." },
      { s: "Station 8 · Infinitivsatz mit „zu“", p: "„Das Wetter ist schön“ hat keine Handlung — bette eine passende Handlung ein.",
        a: "Es ist schön, bei diesem Wetter draußen zu sitzen. / Ich habe keine Lust, bei so schönem Wetter drinnen zu bleiben.",
        w: "Infinitivsatz braucht ein Verb; Komma + „zu + Infinitiv“." },
      { s: "Station 9 · Nebensätze", p: "Je einmal mit wenn (Bedingung), dass (Hoffnung), ob (Zweifel).",
        a: "Ich gehe nur joggen, wenn das Wetter schön ist. / Ich hoffe, dass das Wetter morgen schön wird. / Ich weiß nicht, ob das Wetter am Sonntag schön ist.",
        w: "Nach wenn/dass/ob steht das konjugierte Verb am Satzende." },
      { s: "Station 10 · Passiv", p: "Kein Akkusativobjekt → unpersönliches Passiv aus einer passenden Handlung.",
        a: "Bei schönem Wetter wird viel draußen gegrillt. / Bei Sonne wird im Park Volleyball gespielt.",
        w: "„sein + Adjektiv“ hat kein Passiv; das unpersönliche Passiv braucht kein Subjekt." },
      { s: "Station 11 · Indirekte Rede", p: "Als Aussage des Wetterberichts, Gegenwart und Vergangenheit.",
        a: "Der Wetterbericht sagt, das Wetter sei schön. / Im Bericht hieß es, das Wetter sei am Wochenende schön gewesen.",
        w: "Konj. I: „sei“, „werde“; Vergangenheit immer „sei/habe … + Partizip“." }
    ]},
    { base: "Ich trinke einen Kaffee.", steps: [
      { s: "Station 1 · Grundformen", p: "Aussage, Verneinung, Ja/Nein-Frage.",
        a: "Ich trinke einen Kaffee. / Ich trinke keinen Kaffee. / Trinkst du einen Kaffee?",
        w: "Objekt mit unbestimmtem Artikel verneinen → „kein-“." },
      { s: "Station 2 · Wortwechsel + Angaben", p: "Tausche das Akkusativobjekt (Artikel/Kasus!) und ergänze Zeit/Art.",
        a: "Ich trinke jeden Morgen einen starken Espresso. / … gerade eine Tasse Tee. / … nach dem Essen ein Glas Wasser.",
        w: "Akkusativ bleibt: einen (m.) / eine (f.) / ein (n.)." },
      { s: "Station 3 · Futur I", p: "Zukunft und Vermutung über die Gegenwart.",
        a: "Ich werde gleich einen Kaffee trinken. / Er wird jetzt wohl einen Kaffee trinken.",
        w: "„werden“ Position 2, „trinken“ am Ende." },
      { s: "Station 4 · Modalverben", p: "Drei Modalverben mit unterschiedlicher Bedeutung.",
        a: "Ich möchte einen Kaffee trinken. / Ich will jetzt einen Kaffee trinken. / Ich muss erst einen Kaffee trinken.",
        w: "möchte = höflicher Wunsch, will = Wille, muss = Notwendigkeit." },
      { s: "Station 5 · Vergangenheit", p: "Präteritum und Perfekt.",
        a: "Ich trank einen Kaffee. / Ich habe einen Kaffee getrunken.",
        w: "„trinken“ stark: trank / getrunken, Perfekt mit „haben“." },
      { s: "Station 6 · Modalverb + Vergangenheit", p: "Real (Präteritum) und im Nebensatz mit „weil“ (doppelter Infinitiv).",
        a: "Ich wollte einen Kaffee trinken, aber die Maschine war kaputt. / …, weil ich unbedingt einen Kaffee habe trinken wollen.",
        w: "Im Nebensatz steht „habe“ VOR den beiden Infinitiven." },
      { s: "Station 7 · Konjunktiv II", p: "Gegenwart (würde- und echte Form), Vergangenheit, Wunsch.",
        a: "Ich würde jetzt gern einen Kaffee trinken. (echt: Ich tränke jetzt gern einen Kaffee.) / Ich hätte einen Kaffee trinken können. / Ich wünschte, ich hätte jetzt einen Kaffee.",
        w: "„tränke“ = trank + Umlaut + -e; Alltag meist würde-Form." },
      { s: "Station 8 · Infinitivsatz mit „zu“", p: "Nach „es ist schön“, „keine Zeit haben“, „sich freuen auf“.",
        a: "Es ist schön, morgens in Ruhe einen Kaffee zu trinken. / Ich habe keine Zeit, jetzt einen Kaffee zu trinken. / Ich freue mich darauf, gleich einen Kaffee zu trinken.",
        w: "„sich freuen auf“ → Korrelat „darauf“, dann „…, zu + Infinitiv“." },
      { s: "Station 9 · Nebensätze", p: "Je einmal mit wenn, weil, ob.",
        a: "Wenn ich einen Kaffee trinke, kann ich besser arbeiten. / Ich mache eine Pause, weil ich einen Kaffee trinken will. / Ich weiß nicht, ob ich noch einen Kaffee trinken soll.",
        w: "Verb ans Ende; bei Modalverb das konjugierte Modalverb ganz am Ende." },
      { s: "Station 10 · Passiv", p: "Präsens, Präteritum, Perfekt, und mit Modalverb.",
        a: "Ein Kaffee wird getrunken. / Ein Kaffee wurde getrunken. / Ein Kaffee ist getrunken worden. / Jetzt muss erst mal ein Kaffee getrunken werden.",
        w: "Perfekt mit „ist … worden“ (nicht „geworden“); „ich“ fällt weg." },
      { s: "Station 11 · Indirekte Rede", p: "Gegenwart, Vergangenheit, und ein Passiv-Satz in indirekter Rede.",
        a: "Sie sagt, sie trinke einen Kaffee. / Er sagte, er habe einen Kaffee getrunken. / Jemand hat behauptet, es werde gerade ein Kaffee getrunken.",
        w: "Konj. I: „trinke“, „habe getrunken“, Passiv „werde getrunken“." }
    ]},
    { base: "Mein Kollege hilft mir.", steps: [
      { s: "Station 1 · Grundformen", p: "Aussage, Verneinung, Ja/Nein-Frage.",
        a: "Mein Kollege hilft mir. / Mein Kollege hilft mir nicht. / Hilft mir mein Kollege?",
        w: "„helfen“ verlangt den Dativ (mir)." },
      { s: "Station 2 · Attribute + Angaben", p: "Adjektivattribut, Häufigkeit, Art, Präpositionalobjekt ergänzen.",
        a: "Mein neuer Kollege hilft mir jeden Tag geduldig bei der Arbeit.",
        w: "„mein neuer Kollege“ (gemischte Deklination, Nom. m.); „geduldig“ als Adverb bleibt." },
      { s: "Station 3 · Futur I", p: "Zukunft und beruhigende Vermutung.",
        a: "Mein Kollege wird mir morgen helfen. / Mein Kollege wird mir schon helfen.",
        w: "„schon“ macht daraus eine beruhigende Vermutung." },
      { s: "Station 4 · Modalverben", p: "Fähigkeit, Bereitschaft, fremder Auftrag.",
        a: "Mein Kollege kann mir helfen. / Mein Kollege will mir helfen. / Mein Kollege soll mir helfen.",
        w: "kann = Fähigkeit, will = Bereitschaft, soll = jemand hat es ihm aufgetragen." },
      { s: "Station 5 · Vergangenheit", p: "Präteritum und Perfekt.",
        a: "Mein Kollege half mir. / Mein Kollege hat mir geholfen.",
        w: "half / geholfen, Perfekt mit „haben“; Dativ „mir“ bleibt." },
      { s: "Station 6 · Modalverb + Vergangenheit", p: "Real (Präteritum) und irreal (Konj. II, doppelter Infinitiv).",
        a: "Mein Kollege wollte mir helfen. / Mein Kollege hätte mir helfen können (helfen sollen / helfen müssen).",
        w: "„hätte … helfen können“ = doppelter Infinitiv im Konj. II." },
      { s: "Station 7 · Konjunktiv II", p: "Gegenwart, Vergangenheit, Wunsch.",
        a: "Mein Kollege würde mir helfen, wenn ich ihn fragte. / Mein Kollege hätte mir geholfen, wenn ich gefragt hätte. / Ich wünschte, mein Kollege würde mir helfen.",
        w: "Hauptsatz „würde + Infinitiv“; Vergangenheit „hätte … geholfen“." },
      { s: "Station 8 · Infinitivsatz mit „zu“", p: "Nach „versprechen“, „anbieten“, „nett sein von“.",
        a: "Mein Kollege verspricht mir, mir zu helfen. / Mein Kollege hat angeboten, mir zu helfen. / Es ist nett von meinem Kollegen, mir zu helfen.",
        w: "„Kollege“ ist n-Deklination → „von meinem Kollegen“." },
      { s: "Station 9 · Nebensätze", p: "Grund (weil), Bedingung (wenn), Zweifel (ob).",
        a: "Ich schaffe die Aufgabe, weil mein Kollege mir hilft. / Wenn mein Kollege mir hilft, bin ich schneller fertig. / Ich bin nicht sicher, ob mein Kollege mir heute hilft.",
        w: "Verb ans Ende; nach vorangestelltem Nebensatz folgt sofort das Verb." },
      { s: "Station 10 · Passiv", p: "Nur Dativobjekt → unpersönliches Passiv in drei Zeitstufen.",
        a: "Mir wird (von meinem Kollegen) geholfen. / Mir wurde geholfen. / Mir ist geholfen worden.",
        w: "„mir“ kann nicht Subjekt werden und bleibt Dativ; das Passiv ist subjektlos." },
      { s: "Station 11 · Indirekte Rede", p: "Gegenwart, Vergangenheit, Zukunft — und einmal als Passiv.",
        a: "Mein Kollege sagt, er helfe mir. / Er sagte, er habe mir geholfen. / Er sagte, er werde mir helfen. / Man sagt, mir werde im Team immer gern geholfen.",
        w: "Konj. I: „helfe“, „habe geholfen“, „werde helfen“." }
    ]}
  ];

  var SATZLEITER = [
    { base: "Ich lerne Deutsch.", steps: [
      { s: "Sprosse 2 · Koordination", p: "Hänge mit und / aber / denn je einen zweiten Hauptsatz an.",
        a: "Ich lerne Deutsch, und ich übe jeden Tag. / …, aber es ist nicht immer leicht. / …, denn ich möchte nach Deutschland ziehen.",
        w: "und/aber/oder/denn ändern die Wortstellung nicht — Verb bleibt Position 2." },
      { s: "Sprosse 3 · weil", p: "Gib einen Grund.",
        a: "Ich lerne Deutsch, weil ich nach Deutschland ziehen möchte.",
        w: "Erster Nebensatz: konjugiertes Verb (möchte) ganz ans Ende." },
      { s: "Sprosse 4 · dass", p: "Nach einem Meinungsverb (glauben / finden / denken).",
        a: "Ich glaube, dass Deutsch nicht so schwer ist.",
        w: "dass leitet den Inhaltssatz ein; Verb (ist) ans Ende." },
      { s: "Sprosse 5 · obwohl", p: "Setze einen Gegensatz.",
        a: "Ich lerne Deutsch, obwohl ich wenig Zeit habe.",
        w: "Gleiche Wortstellung wie weil — Verb (habe) ans Ende." },
      { s: "Sprosse 6 · wenn", p: "Stelle den wenn-Satz voran.",
        a: "Wenn ich Zeit habe, lerne ich Deutsch.",
        w: "Vorangestellter Nebensatz → im Hauptsatz sofort das Verb: „…, lerne ich …“." },
      { s: "Sprosse 7 · als", p: "Ein einmaliger Moment in deiner Vergangenheit.",
        a: "Als ich jung war, habe ich nie Deutsch gelernt.",
        w: "als = ein Moment in der Vergangenheit, nicht „wenn“." },
      { s: "Sprosse 8 · Relativsatz", p: "Beschreibe das Nomen „eine Sprache“ selbst.",
        a: "Deutsch ist eine Sprache, die ich schon lange lernen wollte.",
        w: "„die“ = feminin (Sprache), hier Akkusativobjekt; Verb ans Ende." }
    ]},
    { base: "Ich koche jeden Abend.", steps: [
      { s: "Sprosse 2 · Koordination", p: "Mit aber und einer Inversion im zweiten Satz.",
        a: "Ich koche jeden Abend, aber am Wochenende bestelle ich manchmal Essen.",
        w: "Zweiter Hauptsatz beginnt mit „am Wochenende“ → Inversion (bestelle ich)." },
      { s: "Sprosse 3 · weil", p: "Gib einen Grund.",
        a: "Ich koche jeden Abend, weil ich gern esse, was mir schmeckt.",
        w: "Verb (esse) ans Ende; „was mir schmeckt“ = eingeschobener freier Relativsatz." },
      { s: "Sprosse 4 · dass", p: "Nach „finden“.",
        a: "Ich finde, dass Kochen eigentlich ziemlich entspannend ist.",
        w: "„Kochen“ (nominalisiert) = Subjekt; Verb (ist) ans Ende." },
      { s: "Sprosse 5 · obwohl", p: "Setze einen Gegensatz.",
        a: "Ich koche jeden Abend, obwohl ich manchmal keine Zeit habe.",
        w: "Verb (habe) ans Ende — gleiche Struktur wie weil." },
      { s: "Sprosse 6 · wenn", p: "Vorangestellt.",
        a: "Wenn ich müde bin, koche ich trotzdem etwas Einfaches.",
        w: "wenn-Satz im Vorfeld → „…, koche ich …“." },
      { s: "Sprosse 7 · als", p: "Eine Phase in deiner Vergangenheit.",
        a: "Als ich noch bei meinen Eltern gewohnt habe, habe ich nie gekocht.",
        w: "Schriftsprachlich sauberer im Präteritum: „Als ich … wohnte, kochte ich nie.“" },
      { s: "Sprosse 8 · Relativsatz", p: "Beschreibe das Objekt „Gerichte“.",
        a: "Ich koche gern Gerichte, die nicht viel Zeit brauchen.",
        w: "„die“ = Plural (Gerichte), Subjekt; Verb (brauchen) ans Ende." }
    ]},
    { base: "Ich arbeite von zu Hause.", steps: [
      { s: "Sprosse 2 · Koordination", p: "Zweiter Hauptsatz mit einer Angabe im Vorfeld.",
        a: "Ich arbeite von zu Hause, aber manchmal gehe ich ins Büro.",
        w: "„manchmal“ vorn → Inversion (gehe ich)." },
      { s: "Sprosse 3 · weil", p: "Gib einen Grund.",
        a: "Ich arbeite von zu Hause, weil ich dort flexibler bin.",
        w: "Verb (bin) ans Ende." },
      { s: "Sprosse 4 · dass", p: "Mit einem Modalverb im dass-Satz.",
        a: "Ich glaube, dass Homeoffice produktiver sein kann.",
        w: "Bei Modalverb im Nebensatz steht das konjugierte Modalverb (kann) ganz am Ende." },
      { s: "Sprosse 5 · obwohl", p: "Setze einen Gegensatz.",
        a: "Ich arbeite von zu Hause, obwohl ich manchmal die Kollegen vermisse.",
        w: "Verb (vermisse) ans Ende." },
      { s: "Sprosse 6 · wenn", p: "Vorangestellt, mit trennbarem Verb im Hauptsatz.",
        a: "Wenn ich mich konzentrieren muss, schalte ich mein Handy aus.",
        w: "„schalte ich … aus“: Verb zuerst, Präfix am Ende." },
      { s: "Sprosse 7 · als", p: "Eine Phase in deiner Vergangenheit.",
        a: "Als ich noch im Büro gearbeitet habe, bin ich jeden Tag gependelt.",
        w: "Schriftsprachlich: „Als ich … arbeitete, pendelte ich …“." },
      { s: "Sprosse 8 · Relativsatz", p: "Beschreibe „einen Job“.",
        a: "Ich habe einen Job, der mir wirklich Spaß macht.",
        w: "„der“ = maskulin (Job), Subjekt im Nominativ; Verb (macht) ans Ende." }
    ]}
  ];

  return { kreis: SATZKREIS, leiter: SATZLEITER };
})();
